---
- name: Disable SELINUX
  selinux:
    state: disabled
  tags:
    - candlepin
    - candlepin-root

- name: Enable & Start the haveged entropy service
  service:
    name: haveged
    enabled: yes
    state: started
  tags:
    - candlepin
    - candlepin-root

- name: Add remote debugging config to tomcat
  lineinfile:
    dest: /etc/tomcat/tomcat.conf
    line: "JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n"
  tags:
    - candlepin
    - candlepin-root

- name: Initiate database
  command: service postgresql initdb
  args:
    creates: /var/lib/pgsql/data/postgresql.conf
  environment:
    PATH: /usr/sbin:{{ ansible_env.PATH }}
  tags:
    - candlepin
    - candlepin-root

- name: Set postgresql to trust
  replace:
    dest: /var/lib/pgsql/data/pg_hba.conf
    regexp: '(ident|peer)'
    replace: 'trust'
    backup: yes
  tags:
    - candlepin
    - candlepin-root

- name: Set postgresql to accept RH internal connections
  lineinfile:
    dest: /var/lib/pgsql/data/pg_hba.conf
    line: "host    all         all         10.0.0.0/8            md5"
  tags:
    - candlepin
    - candlepin-root

- name: Set postgresql listen on all addresses
  lineinfile:
    dest: /var/lib/pgsql/data/postgresql.conf
    line: "listen_addresses = '*'"
  tags:
    - candlepin
    - candlepin-root

- name: Start PostgreSQL and enable at boot
  service:
    name: postgresql
    enabled: yes
    state: started
  tags:
    - candlepin
    - candlepin-root

- name: Check if firewalld is on
  shell: "systemctl is-active firewalld.service"
  ignore_errors: true
  register: firewalld_status
  tags:
    - candlepin
    - candlepin-root

- name: punch holes in firewall
  firewalld:
    port: "{{item}}/tcp"
    permanent: True
    state: enabled
    immediate: True
  with_items:
    - 22
    - 5432
    - 443
    - 8443
    - 8080
    - 5005
    - 8161
  when: firewalld_status.rc == 0
  tags:
    - candlepin
    - candlepin-root

- name: Install gem dependencies
  shell: "gem install {{item}}"
  with_items:
    - json_pure
    - rubygems-update
    - --user-install executable-hooks
  tags:
    - candlepin
    - candlepin-root

- name: Gem refreshing
  shell: |
    gem update --system
  tags:
    - candlepin
    - candlepin-root

- name: Create postgresql user
  postgresql_user:
    name: candlepin
    password: candlepin
    role_attr_flags: CREATEDB
  tags:
    - candlepin
    - candlepin-root

- name: Create postgresql db
  postgresql_db:
    name: candlepin
    owner: candlepin
  tags:
    - candlepin
    - candlepin-root

- name: Install six python module for translations
  pip:
    name: six
  tags:
    - candlepin
    - candlepin-root
    - python-deps

- name: Set JAVA_HOME
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^JAVA_HOME'
    line: 'JAVA_HOME=/usr/lib/jvm/java-1.8.0/'
  tags:
    - candlepin
    - candlepin-user

- name: Run Bundle install
  shell: |
    bundle install --without proton --system --gemfile=/vagrant/Gemfile
  args:
    chdir: "{{candlepin_checkout}}"
